version: "3"
services:
  joke-service:
    build: ./services/joke-service
    depends_on: [postgres, redis, rabbitmq]
  laugh-service:
    build: ./services/laugh-service
    depends_on: [rabbitmq]
  delivery-service:
    build: ./services/delivery-service
  timing-service:
    build: ./services/timing-service
  postgres:
    image: postgres:9.6
  redis:
    image: redis:3.2
  rabbitmq:
    image: rabbitmq:3.6-management
  consul:
    image: consul:0.8
