name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: pip install -r requirements.txt
      - run: python validate.py
      - run: pytest tests/
      - run: python -c "import enterprise.utils2"  # canary
